<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ThirteenThirtyOne.Game.Domain/ThirteenThirtyOne.Game.Domain.csproj" />
    <ProjectReference Include="../../src/ThirteenThirtyOne.Game.Engine/ThirteenThirtyOne.Game.Engine.csproj" />
    <ProjectReference Include="../../src/ThirteenThirtyOne.Application/ThirteenThirtyOne.Application.csproj" />
    <ProjectReference Include="../../src/ThirteenThirtyOne.Infrastructure/ThirteenThirtyOne.Infrastructure.csproj" />
    <ProjectReference Include="../../src/ThirteenThirtyOne.Protocol/ThirteenThirtyOne.Protocol.csproj" />
    <ProjectReference Include="../../src/ThirteenThirtyOne.GameBackend/ThirteenThirtyOne.GameBackend.csproj" />
  </ItemGroup>
</Project>
